# Render Blueprint: Crypto Alerts
# Docs: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: crypto-alerts-web
    env: python
    plan: starter  # change to 'standard' or higher if needed
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn server_combined:app --bind 0.0.0.0:$PORT --workers 2 --timeout 60
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: ENV
        value: production
      - key: DATABASE_URL
        sync: false           # set in Dashboard after attaching Managed Postgres
      - key: ALERTS_SECRET
        sync: false           # set in Dashboard
      - key: BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: STRIPE_SECRET
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false

  - type: worker
    name: crypto-alerts-worker
    env: python
    plan: starter
    region: frankfurt
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python worker.py
    autoDeploy: true
    envVars:
      - key: ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: WORKER_INTERVAL_SECONDS
        value: "60"
