
services:
  - type: web
    name: crypto-alerts-web
    env: python
    region: frankfurt
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker server_combined:app --bind 0.0.0.0:$PORT --workers 2 --timeout 60
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: ALERTS_SECRET
        sync: false
      - key: PAYPAL_ENV
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: PAYPAL_WEBHOOK_ID
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false

  - type: worker
    name: crypto-alerts-daemon
    env: python
    region: frankfurt
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python daemon.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: WEB_URL
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: WORKER_INTERVAL_SECONDS
        value: "60"
