# Render Blueprint: Crypto Alerts (Web API + Background Worker + Telegram Bot)
# Όλα τα services στο Free plan με ρητά δηλωμένα env vars.

services:
  # ─────────────────────────────── WEB (FastAPI) ───────────────────────────────
  - type: web
    name: crypto-alerts-web
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    # ASGI (FastAPI) μέσω Gunicorn + Uvicorn worker
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker server_combined:app --bind 0.0.0.0:$PORT --workers 2 --timeout 60
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      # Σταθερές (βάζουμε τιμή εδώ)
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: ENV
        value: production

      # Χρειάζονται χειροκίνητη τιμή ΜΕΤΑ το create (sync: false)
      - key: DATABASE_URL              # π.χ. postgresql://USER:P%40SS@HOST:5432/DB?sslmode=require
        sync: false
      - key: ADMIN_KEY                 # για /admin/* (ως ?key= ή header x-admin-key)
        sync: false
      - key: ALERTS_SECRET             # για /cron (αν το χρησιμοποιήσεις)
        sync: false
      - key: BOT_TOKEN                 # Telegram bot token (αν το web στέλνει/χρειάζεται)
        sync: false
      - key: TELEGRAM_CHAT_ID          # προαιρετικό default chat id
        sync: false
      - key: STRIPE_SECRET             # προαιρετικό (αν βάλεις Stripe)
        sync: false
      - key: STRIPE_WEBHOOK_SECRET     # προαιρετικό (αν βάλεις Stripe)
        sync: false

  # ───────────────────────────── BACKGROUND WORKER ─────────────────────────────
  - type: worker
    name: crypto-alerts-worker
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python worker.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: ENV
        value: production

      - key: DATABASE_URL
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false

      # Ρυθμίζει κάθε πόσα δευτερόλεπτα τρέχει ο κύκλος του worker
      - key: WORKER_INTERVAL_SECONDS
        value: "60"

  # ─────────────────────────────── TELEGRAM BOT ────────────────────────────────
  - type: worker
    name: crypto-alerts-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: ENV
        value: production

      - key: DATABASE_URL              # ώστε το bot να διαβάζει/γράφει στη DB
        sync: false
      - key: BOT_TOKEN                 # από @BotFather
        sync: false
      - key: TELEGRAM_CHAT_ID          # προαιρετικό default chat για ειδοποιήσεις
        sync: false
