services:
  - type: web
    name: crypto-alerts-web
    env: python
    plan: free        # βάλε starter αν θες 24/7
    buildCommand: "pip install -r requirements.txt"
    startCommand: >
      gunicorn server_combined:app
      -k uvicorn.workers.UvicornWorker
      --bind 0.0.0.0:$PORT
      --workers 2
      --timeout 60
      --graceful-timeout 30
      --keep-alive 5
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: WEB_URL
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: PAYPAL_SUBSCRIBE_URL
        sync: false
      - key: FREE_ALERT_LIMIT
        value: "3"
      - key: WORKER_INTERVAL_SECONDS
        value: "60"

  - type: worker
    name: crypto-alerts-daemon
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python daemon.py"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: WEB_URL
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: PAYPAL_SUBSCRIBE_URL
        sync: false
      - key: FREE_ALERT_LIMIT
        value: "3"
      - key: WORKER_INTERVAL_SECONDS
        value: "60"
      - key: RUN_BOT
        value: "1"
      - key: RUN_ALERTS
        value: "1"
