# Render Blueprint: Crypto Alerts (Web API + Worker + Telegram Bot)
# Region: Frankfurt • Plan: Free • Payments: PayPal

services:
  # ─────────────────────────────── WEB (FastAPI) ───────────────────────────────
  - type: web
    name: crypto-alerts-web
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker server_combined:app --bind 0.0.0.0:$PORT --workers 2 --timeout 60
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: ENV
        value: production

      # Database & secrets
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: ALERTS_SECRET
        sync: false

      # Telegram (optional, αν θες να στέλνει μηνύματα το Web)
      - key: BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false

      # PayPal
      - key: PAYPAL_ENV
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: PAYPAL_WEBHOOK_ID
        sync: false

  # ───────────────────────────── BACKGROUND WORKER ─────────────────────────────
  - type: worker
    name: crypto-alerts-worker
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python worker.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: ENV
        value: production

      - key: DATABASE_URL
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false

      - key: WORKER_INTERVAL_SECONDS
        value: "60"

  # ─────────────────────────────── TELEGRAM BOT ────────────────────────────────
  - type: worker
    name: crypto-alerts-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: ENV
        value: production

      - key: DATABASE_URL
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: WEB_URL
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
