services:
  - type: web
    name: crypto-alerts-bot
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: bash -lc "uvicorn web_health:app --host 0.0.0.0 --port $PORT & python daemon.py"
    autoDeploy: true
    envVars:
      - key: WEB_CONCURRENCY
        value: "1"
      - key: RUN_BOT
        value: "1"
      - key: RUN_ALERTS
        value: "0"
      # The following should be set in dashboard or from .env (do not commit secrets):
      # BOT_TOKEN, DATABASE_URL, ADMIN_TELEGRAM_IDS, etc.

  - type: worker
    name: crypto-alerts-worker
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
    autoDeploy: true
    envVars:
      - key: RUN_BOT
        value: "0"
      - key: RUN_ALERTS
        value: "1"
      - key: WORKER_INTERVAL_SECONDS
        value: "60"
